# -----------------------------------------------------------------------------
# definitions and Terraform backend
# -----------------------------------------------------------------------------
locals {
  common_tags = {
    env = "${var.abk_deployment_env}"
  }
}

provider "aws" {
  region                      = var.abk_deployment_region
  skip_credentials_validation = false
  skip_metadata_api_check     = false
  skip_region_validation      = false
}

# Backend configuration will be generated by deploy-001_setup-env.sh


# -----------------------------------------------------------------------------
# modules
# -----------------------------------------------------------------------------
module "abk_s3_releases_bucket_module" {
  source                 = "../../../templates/s3-private-bucket"
  private_s3_bucket_name = var.abk_service_deployment_bucket_name
  enable_versioning      = var.enable_versioning
}
