# -----------------------------------------------------------------------------
# definitions and Terraform backend
# -----------------------------------------------------------------------------
locals {
  common_tags = {
    env = "${var.abk_deployment_env}"
  }
}

# Backend and provider configuration will be generated by deploy-001_setup-env.sh


# -----------------------------------------------------------------------------
# modules
# -----------------------------------------------------------------------------
module "abk_s3_releases_bucket_module" {
  source                 = "../../../templates/s3PrivateBucket"
  private_s3_bucket_name = var.abk_service_deployment_bucket_name
  enable_versioning      = var.enable_versioning
}
